name = "image-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = []

[env.development]
name = "image-worker-dev"
vars = { LOG_LEVEL = "debug" }

[env.staging]
name = "image-worker-staging"
vars = { LOG_LEVEL = "info" }

[env.production]
name = "image-worker"
vars = { LOG_LEVEL = "info" }
